# SwiftLint configuration for Junkpile iOS app
# Documentation: https://github.com/realm/SwiftLint

# Paths to include
included:
  - Junkpile

# Paths to exclude
excluded:
  - Junkpile/Resources
  - build
  - DerivedData
  - .build

# Disabled rules (too strict for initial development)
disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - todo  # Allow TODO comments during development

# Opt-in rules to enable
opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - explicit_init
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Rule configurations
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ok
    - to
    - x
    - y
    - i
    - j
    - db

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

# Customizations
force_cast: warning
force_try: warning
force_unwrapping: warning

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"
